# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedtime', models.TimeField()),
                ('exit_bed_time', models.TimeField()),
                ('ease_of_sleep', models.IntegerField(choices=[(1, 'Easily'), (2, 'After Some Time'), (3, 'With Difficulty')], default=2)),
                ('times_awoken', models.IntegerField()),
                ('minutes_awake', models.IntegerField()),
                ('total_sleep_time', models.IntegerField()),
                ('factors_disturbing_sleep', models.TextField()),
                ('subjective_waking_mood_rating', models.CharField(choices=[('RE', 'Refreshed'), ('SR', 'Somewhat Refreshed'), ('FA', 'Fatigued')], default='SR', max_length=2)),
                ('notes', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('caffeine_consumption_morning', models.BooleanField()),
                ('caffeine_consumption_evening', models.BooleanField()),
                ('caffeine_consumption_afternoon', models.BooleanField()),
                ('exercised_morning', models.BooleanField()),
                ('exercised_afternoo', models.BooleanField()),
                ('exercised_evening', models.BooleanField()),
                ('todays_medications', models.TextField()),
                ('took_a_nap', models.BooleanField()),
                ('length_of_nap', models.IntegerField()),
                ('likelihood_of_dosing', models.CharField(choices=[('NC', 'No Chance'), ('SC', 'Slight Chance'), ('MC', 'Moderate_Chance'), ('HC', 'High Chance')], default='SC', max_length=2)),
                ('days_mood', models.CharField(choices=[('VP', 'Very Pleasant'), ('PL', 'Pleasant'), ('UP', 'Unpleasant'), ('VU', 'Very Unpleasant')], default='PL', max_length=4)),
                ('pre_bedtime_consumption', models.CharField(choices=[('AL', 'Alcohol'), ('HM', 'Heavy Meal'), ('CA', 'Caffeine'), ('NA', 'Not Applicable')], default='NA', max_length=4)),
                ('bedtime_routine', models.TextField()),
            ],
        ),
    ]
